# Generated by Django 5.2.8 on 2025-11-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
              INSERT INTO store_collection (title) VALUES ('test');
            """, """
                DELETE FROM store_collection WHERE title='test';
            """)
    ]
