# Generated by Django 5.2.8 on 2025-11-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20251115_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product',
            new_name='featured_product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
    ]
