# Generated by Django 5.2.8 on 2025-11-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_featured_product_collection_featured_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product_id',
            new_name='featured_product',
        ),
    ]
