# Generated by Django 5.2.8 on 2025-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_featured_product_id_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collelction',
            new_name='collelction_id',
        ),
    ]
