# Generated by Django 5.2.8 on 2025-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_collelction_product_collelction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collelction_id',
            new_name='collelction',
        ),
    ]
