# Generated by Django 5.2.8 on 2025-11-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_collelction_id_product_collelction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collelction',
            new_name='collection',
        ),
    ]
