# Generated by Django 5.2.8 on 2025-11-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_collelction_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
