# Generated by Django 5.2.8 on 2025-11-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
